server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mmd.mmdshop.dbdo;                 # 所有Entity别名类所在包com.mmd.mmdshop.dbdo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
mybatis-plus:
  type-aliases-package: com.mmd.mmdshop.dbdo;
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
spring:
   application:
    name: mmdshop-provider 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mmd_demo?allowMultiQueries=true&amp;useUnicode=true&characterEncoding=UTF-8              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   druid:
    test-on-borrow: false
    test-while-idle: true
    test-on-return: false
   http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
                
logging:
  level:
    com.mmd.mmdshop.dao : debug
   