server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  
spring:
 mvc:
  static-path-pattern: /**
 http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
 redis:
    database: 0         # Redis数据库索引（默认为0）  
    host: 192.168.1.9  # Redis服务器地址  
    port: 6379          # Redis服务器连接端口
    password: 123456    # Redis服务器连接密码（默认为空）
    